name = "cynkeyo/build_test"
version = "0.1.0"
description = "Roblox Studio plugin that provides the user with playtest mode building tools that syncs up changes to edit mode."
authors = ["cynkeyo"]
license = "MIT"

[target]
environment = "roblox"
build_files = ["src"]

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }

[dependencies]
react = { wally = "jsdotlua/react", version = "^17.2.1" }
studiocomponents = { wally = "sircfenner/studiocomponents", version = "^1.2.0" }
goodsignal = { wally = "stravant/goodsignal", version = "^0.3.0" }
ui-labs = { wally = "pepeeltoro41/ui-labs", version = "^2.4.0" }
